# Generated by Django 3.0.2 on 2020-02-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_text', models.TextField()),
                ('true_fact', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='facts.Category')),
            ],
        ),
    ]
