# Generated by Django 3.0.2 on 2020-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='facts',
            field=models.ManyToManyField(to='facts.Fact'),
        ),
    ]
